version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - EKA_MCP_URL=${EKA_MCP_URL}
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"